In [43]:
import numpy as np
from PIL import Image
from sklearn.metrics import accuracy_score

# Sigma
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

def rgb_to_bynar(r,g,b):
    if ((r+g+b)/3)<100:
        return 1
    return 0

def get_image_size(filename):
    image = Image.open(filename)
    row,col=image.size
    return row,col

def read_data(filename):  
    y=[]
    image = Image.open(filename)
    row,col = get_image_size(filename)
    pixels = image.load()

    for i in range(row):
        for j in range(col):
            r,g,b = pixels[i,j]
            color = rgb_to_bynar(r,g,b)           
            y.append(color)
    return y


zero1=read_data('img/zero1.png')
zero2=read_data('img/zero2.png')
zero3=read_data('img/zero3.png')
zero4=read_data('img/zero4.png')
unu1=read_data('img/unu1.png')
unu2=read_data('img/unu2.png')
unu3=read_data('img/unu3.png')
unu4=read_data('img/unu4.png')
doi1=read_data('img/doi1.png')
doi2=read_data('img/doi2.png')
doi3=read_data('img/doi3.png')
doi4=read_data('img/doi4.png')
trei1=read_data('img/trei1.png')
trei2=read_data('img/trei2.png')
trei3=read_data('img/trei3.png')
trei4=read_data('img/trei4.png')
patru1=read_data('img/patru1.png')
patru2=read_data('img/patru2.png')
patru3=read_data('img/patru3.png')
patru4=read_data('img/patru4.png')
cinci1=read_data('img/cinci1.png')
cinci2=read_data('img/cinci2.png')
cinci3=read_data('img/cinci3.png')
cinci4=read_data('img/cinci4.png')


X1=np.vstack((cinci1,cinci2,cinci3,cinci4,patru1,patru2,patru3,patru4,trei1,trei2,trei3,trei4,doi1,doi2,doi3,doi4,unu1,unu2,unu3,unu4,zero1,zero2,zero3,zero4))
print len(X1[:,1])

24


In [49]:
# Setul datelor de intrare 
X = np.array(X1)

# Setul datelor de esire             
y= np.array([  [1,0,1],
               [1,0,1],
               [1,0,1],
               [1,0,1],
                [1,0,0],
                [1,0,0],
                [1,0,0],
                [1,0,0],
             [0,1,1],
             [0,1,1],
             [0,1,1],
             [0,1,1],
                 [0,1,0],
                 [0,1,0],
                 [0,1,0],
                 [0,1,0],
             [0,0,1],
             [0,0,1],
             [0,0,1],
             [0,0,1],
                 [0,0,0],
                 [0,0,0],
                 [0,0,0],
                 [0,0,0]
            ])



#Pentru ca numerele random sa fie mai detectabile
np.random.seed(1)

# Initialzam ponderile cu media 0
syn0 = 2*np.random.random((100,3)) - 1
i=0
for iter in xrange(5000):
    
    # прямое распространение
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
     
    
    # Calculam eroarea 
    l1_error = y - l1
   
    
    if iter%10==0:
        print'\n'
        print 'Iteratia'
        print iter
        print l1_error 
       

    # Imultim eroarea c
    l1_delta = l1_error * nonlin(l1,True)
    
    # Ajustam ponderea
    #print len(l1_delta[:,1])
    #print len(l0.T[:,1])
    syn0 += np.dot(l0.T,l1_delta)






Iteratia
0
[[ 0.61150025 -0.65169723  0.43321354]
 [ 0.44169401 -0.41418042  0.48647425]
 [ 0.67292564 -0.649031    0.55098377]
 [ 0.70285934 -0.40871335  0.4228326 ]
 [ 0.5        -0.5        -0.5       ]
 [ 0.17271731 -0.49811329 -0.12583398]
 [ 0.38068738 -0.42301815 -0.54300777]
 [ 0.37715905 -0.61111369 -0.68278759]
 [-0.58531629  0.69304786  0.18403667]
 [-0.37506798  0.87397848  0.0886511 ]
 [-0.47553851  0.72923092  0.30791472]
 [-0.5         0.5         0.5       ]
 [-0.40678497  0.39401076 -0.32077233]
 [-0.32613278  0.29625595 -0.59715776]
 [-0.32422659  0.68362481 -0.28618869]
 [-0.49578668  0.70956554 -0.53699109]
 [-0.38041914 -0.5470388   0.56561973]
 [-0.35225516 -0.54058994  0.28089227]
 [-0.18178362 -0.21748891  0.51522769]
 [-0.15799109 -0.60108216  0.68836408]
 [-0.31732266 -0.73137205 -0.69977321]
 [-0.76856631 -0.9531741  -0.55835884]
 [-0.42742252 -0.88513041 -0.66802376]
 [-0.69141845 -0.53677322 -0.2700716 ]]


Iteratia
10
[[ 0.14512789 -0.00538039  0.0764460

In [46]:
test_cinci= np.vstack(read_data('img/cinci_test.png')).T
print nonlin(np.dot(test_cinci,syn0))
print [1,0,1]

[[ 0.89415965  0.14981418  0.74138133]]
[1, 0, 1]


In [47]:
test_patru= np.vstack(read_data('img/patru_test.png')).T
print nonlin(np.dot(test_patru,syn0))
print [1,0,0]

[[ 0.93755652  0.16264817  0.38502354]]
[1, 0, 0]


In [48]:
test_trei= np.vstack(read_data('img/trei_test.png')).T
print nonlin(np.dot(test_trei,syn0))
print [0,1,1]

[[ 0.85265786  0.19071205  0.11070637]]
[0, 1, 1]


In [15]:
test_doi= np.vstack(read_data('img/doi_test.png')).T
print nonlin(np.dot(test_doi,syn0))
print [0,1,0]

[[ 0.22995888  0.76874997  0.33328742]]
[0, 1, 0]


In [13]:
test_unu= np.vstack(read_data('img/unu_test.png')).T
print nonlin(np.dot(test_unu,syn0))
print [0,0,1]

[[ 0.36228238  0.43199584  0.61501129]]
[0, 0, 1]


In [14]:
test_zero= np.vstack(read_data('img/zero_test.png')).T
print nonlin(np.dot(test_zero,syn0))
print [0,0,0]

[[ 0.1469778   0.23986277  0.33762415]]
[0, 0, 0]
