In [51]:
import numpy as np
from PIL import Image
from sklearn.metrics import accuracy_score

# Sigma
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

def rgb_to_bynar(r,g,b):
    if ((r+g+b)/3)<100:
        return 1
    return 0

def get_image_size(filename):
    image = Image.open(filename)
    row,col=image.size
    return row,col

def read_data(filename):  
    y=[]
    image = Image.open(filename)
    row,col = get_image_size(filename)
    pixels = image.load()

    for i in range(row):
        for j in range(col):
            r,g,b = pixels[i,j]
            color = rgb_to_bynar(r,g,b)           
            y.append(color)
    return y


zero1=read_data('img/zero1.png')
zero2=read_data('img/zero2.png')
zero3=read_data('img/zero3.png')
zero4=read_data('img/zero4.png')
unu1=read_data('img/unu1.png')
unu2=read_data('img/unu2.png')
unu3=read_data('img/unu3.png')
unu4=read_data('img/unu4.png')
doi1=read_data('img/doi1.png')
doi2=read_data('img/doi2.png')
doi3=read_data('img/doi3.png')
doi4=read_data('img/doi4.png')
trei1=read_data('img/trei1.png')
trei2=read_data('img/trei2.png')
trei3=read_data('img/trei3.png')
trei4=read_data('img/trei4.png')
patru1=read_data('img/patru1.png')
patru2=read_data('img/patru2.png')
patru3=read_data('img/patru3.png')
patru4=read_data('img/patru4.png')
cinci1=read_data('img/cinci1.png')
cinci2=read_data('img/cinci2.png')
cinci3=read_data('img/cinci3.png')
cinci4=read_data('img/cinci4.png')


X1=np.vstack((cinci1,cinci2,cinci3,cinci4,patru1,patru2,patru3,patru4,trei1,trei2,trei3,trei4,doi1,doi2,doi3,doi4,unu1,unu2,unu3,unu4,zero1,zero2,zero3,zero4))
print len(X1[:,1])

24


In [52]:
# Setul datelor de intrare 
X = np.array(X1)

# Setul datelor de esire             
y= np.array([  [1,0,1],
               [1,0,1],
               [1,0,1],
               [1,0,1],
                [1,0,0],
                [1,0,0],
                [1,0,0],
                [1,0,0],
             [0,1,1],
             [0,1,1],
             [0,1,1],
             [0,1,1],
                 [0,1,0],
                 [0,1,0],
                 [0,1,0],
                 [0,1,0],
             [0,0,1],
             [0,0,1],
             [0,0,1],
             [0,0,1],
                 [0,0,0],
                 [0,0,0],
                 [0,0,0],
                 [0,0,0]
            ])



#Pentru ca numerele random sa fie mai detectabile
np.random.seed(1)

# Initialzam ponderile cu media 0
syn0 = 2*np.random.random((100,3)) - 1
i=0
for iter in xrange(5000):
    
    # прямое распространение
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
     
    
    # Calculam eroarea 
    l1_error = y - l1
   
    
    #if iter%10==0:
        #print'\n'
        #print 'Iteratia'
        #print iter
        #print l1_error 
       

    # Imultim eroarea c
    l1_delta = l1_error * nonlin(l1,True)
    
    # Ajustam ponderea
    #print len(l1_delta[:,1])
    #print len(l0.T[:,1])
    syn0 += np.dot(l0.T,l1_delta)




In [46]:
test_cinci= np.vstack(read_data('img/cinci_test.png')).T
print nonlin(np.dot(test_cinci,syn0))
print [1,0,1]

[[ 0.89415965  0.14981418  0.74138133]]
[1, 0, 1]


In [47]:
test_patru= np.vstack(read_data('img/patru_test.png')).T
print nonlin(np.dot(test_patru,syn0))
print [1,0,0]

[[ 0.93755652  0.16264817  0.38502354]]
[1, 0, 0]


In [48]:
test_trei= np.vstack(read_data('img/trei_test.png')).T
print nonlin(np.dot(test_trei,syn0))
print [0,1,1]

[[ 0.85265786  0.19071205  0.11070637]]
[0, 1, 1]


In [15]:
test_doi= np.vstack(read_data('img/doi_test.png')).T
print nonlin(np.dot(test_doi,syn0))
print [0,1,0]

[[ 0.22995888  0.76874997  0.33328742]]
[0, 1, 0]


In [13]:
test_unu= np.vstack(read_data('img/unu_test.png')).T
print nonlin(np.dot(test_unu,syn0))
print [0,0,1]

[[ 0.36228238  0.43199584  0.61501129]]
[0, 0, 1]


In [14]:
test_zero= np.vstack(read_data('img/zero_test.png')).T
print nonlin(np.dot(test_zero,syn0))
print [0,0,0]

[[ 0.1469778   0.23986277  0.33762415]]
[0, 0, 0]
